--- 

- hosts: all
  gather_facts: no
  user: root
  vars_file: 
  - vars.yml


  tasks:
  - name: Create a boot password
    expect:  
     command: grub2-setpassword
     responses:
      Enter password: "{{ grub_password} }"
      Reenter password: "{{ grub_password }}"
  
  - name: Verify
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
