--- 

- hosts: all
  gather_facts: no
  user: root
  vars_files: 
  - vars.yml

  tasks:  
  - name: Install pip
    package:
      name: /usr/bin/pip
      state: latest

  - name: Install the pexpect module
    pip:
      name: pexpect
  
  - name: Create a boot password
    expect:  
     command: grub2-setpassword
     responses:
      Enter password: "{{ grub_password }}"
      Confirm password: "{{ grub_password }}"
  
  - name: Recreate the grub config with grub2-mkconfig
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
